# This workflow will build an Xcode project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-xcode

name: Xcode Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest # Or macos-13 if you need a specific version

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Optional: Install xcpretty for cleaner output
    - name: Install xcpretty
      run: gem install xcpretty

    # Optional: Select a specific Xcode version if needed
    # - name: Select Xcode version
    #   run: sudo xcode-select -s /Applications/Xcode_XX.Y.app/Contents/Developer

    - name: Build and Test
      run: |
        set -o pipefail && \
        xcodebuild test -project closeup.xcodeproj -scheme closeup \
        -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
        CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO | xcpretty
